import Vue from 'vue';
import FormBooleanField from './components/form/BooleanField.vue';
import ShowBooleanField from './components/show/BooleanField.vue';
import IndexBooleanField from './components/index/BooleanField.vue';
import FormSelectField from './components/form/SelectField.vue';
import ShowSelectField from './components/show/SelectField.vue';
import IndexSelectField from './components/index/SelectField.vue';
import FormTextField from './components/form/TextField.vue';
import ShowTextField from './components/show/TextField.vue';
import IndexTextField from './components/index/TextField.vue';
import FormTextareaField from './components/form/TextareaField.vue';
import ShowTextareaField from './components/show/TextareaField.vue';
import IndexTextareaField from './components/index/TextareaField.vue';

Vue.component('form-boolean-field', FormBooleanField);
Vue.component('show-boolean-field', ShowBooleanField);
Vue.component('index-boolean-field', IndexBooleanField);
Vue.component('form-select-field', FormSelectField);
Vue.component('show-select-field', ShowSelectField);
Vue.component('index-select-field', IndexSelectField);
Vue.component('form-text-field', FormTextField);
Vue.component('show-text-field', ShowTextField);
Vue.component('index-text-field', IndexTextField);
Vue.component('form-textarea-field', FormTextareaField);
Vue.component('show-textarea-field', ShowTextareaField);
Vue.component('index-textarea-field', IndexTextareaField);
